#!/usr/bin/python3

import json
import os
import sys
import types
from typing import Any

in_, out = sys.argv[1:3]
raw_input = open(in_, encoding="utf-8").read()
helper_output: dict[str, Any] = {}

try:
    _mock = types.ModuleType("pyotherside")
    setattr(_mock, "send", lambda *a, **kw: None)
    sys.modules["pyotherside"] = _mock

    src_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src")
    if src_dir not in sys.path:
        sys.path.insert(0, src_dir)

    from constants import APP_NAME
    from ut_components import setup

    setup(APP_NAME)

    from push_helper import build_postal_output

    helper_output = build_postal_output(raw_input)
except Exception:
    helper_output = {}

with open(out, "w", encoding="utf-8") as f:
    f.write(json.dumps(helper_output))

try:
    from events import process_events_once

    process_events_once()
except Exception:
    pass
